const MONGODB_HOST = process.env.MONGODB_HOST || 'localhost';
const MONGODB_PORT = process.env.MONGODB_PORT;
const MONGODB_ADMIN_LOGIN_DB = process.env.MONGODB_ADMIN_LOGIN_DB || 'admin';
const MONGODB_ADMIN_USER = process.env.MONGODB_ADMIN_USER;
const MONGODB_ADMIN_PASS = process.env.MONGODB_ADMIN_PASS;
const MONGODB_LOGIN_DB = process.env.MONGODB_LOGIN_DB || 'admin';
const MONGODB_USER = process.env.MONGODB_USER;
const MONGODB_PASS = process.env.MONGODB_PASS;
const MONGODB_NAME = process.env.MONGODB_NAME;
const MONGODB_AUTH_MECHANISM = process.env.MONGODB_ADMIN_AUTH_MECHANISM;
const MONGODB_ADMIN_AUTH_MECHANISM = process.env.MONGODB_ADMIN_AUTH_MECHANISM || MONGODB_AUTH_MECHANISM;
const MONGODB_USER_AUTH_MECHANISM = process.env.MONGODB_USER_AUTH_MECHANISM || MONGODB_AUTH_MECHANISM;

const MONGODB_URL = (() => {
  if (process.env.MONGODB_URL) {
    return process.env.MONGODB_URL;
  }
  return `mongodb://${MONGODB_HOST}${MONGODB_PORT ? (':' + MONGODB_PORT) : ''}`;
})();

module.exports = {
  MONGODB_URL,
  MONGODB_HOST,
  MONGODB_ADMIN_LOGIN_DB,
  MONGODB_ADMIN_USER,
  MONGODB_ADMIN_PASS,
  MONGODB_LOGIN_DB,
  MONGODB_USER,
  MONGODB_PASS,
  MONGODB_NAME,
  MONGODB_AUTH_MECHANISM,
  MONGODB_ADMIN_AUTH_MECHANISM,
  MONGODB_USER_AUTH_MECHANISM
};
