on:
  push: {}
jobs:
  push_to_registry:
    name: Push Docker image to gchr.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Image Name for master branch
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          echo "NEED_IMAGE_PUSH=true" >> $GITHUB_ENV
          echo "IMAGE_VERSION=commit-${GITHUB_SHA::8}" >> $GITHUB_ENV
      - name: Set Image Name for tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "NEED_IMAGE_PUSH=true" >> $GITHUB_ENV
          echo "IMAGE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: ${{ env.NEED_IMAGE_PUSH == 'true' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - run: |
          echo ".git" > .dockerignore
          echo ".github" > .dockerignore
          echo "Dockerfile" > .dockerignore
          cat .gitignore >> .dockerignore
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha
          push: ${{ env.NEED_IMAGE_PUSH == 'true' }}
          tags: |
            ${{ env.LATEST_IMAGE_NAME }}
            ghcr.io/${{ github.repository_owner }}/mongodb-init-helper:${{ env.IMAGE_VERSION }}